### ISSUE TITLE
wireframe - homepage - draft - v01

### ISSUE THREAD

**Issue by Hadi-Khatib** [syrianarchive/syrianarchive-http#1]
![homepage](https://user-images.githubusercontent.com/8692315/30175275-3eaeaa42-93fe-11e7-9cd2-0b3efc36b1ea.png)

**Comment by nikonikoniko** [comment]
Honestly, I find the charts not so good.  They don't really say anything, because we dont have a full count of incidents in the war.  Currently it is just 'how much of our database has been tagged with this item' - which is not that useful of a statistic

**Comment by j-deutch** [comment]
I disagree. I think the charts are good but the wording needs adjustment. We don't have a list of full count of incidents in the war, but we do have a list of what we've categorised. And that is very useful as a statistic. It should be worded not as "Illegal weapons have been used ### times" as the following, but rather "Of content verified by the Syrian Archive, the use of illegal weapons has been determined ### times."

**Comment by j-deutch** [comment]
And Database is one word not Data Base

**Comment by nikonikoniko** [comment]
Yes but thats exactly what i mean.

the NUMBER of items that we have in a certain category is very useful.
the PERCENTAGE is not useful at all.

a pie chart is for showing parts of a whole. the % of our dataset that includes chemical weapons is a meaningless statistic.  because its only of the ones we have verified, which we have sometimes chosen based on an investigation.

**Comment by nikonikoniko** [comment]
just tell me what exactly a percentage based chart is trying to say.  

I am happy to do it if others think i should (but a separate issue is that wont be done by launch as it's not so easy)

**Comment by j-deutch** [comment]
But it's percentage of verified dataset. And percentage of verified units is a totally useful statistic, or?

**Comment by nikonikoniko** [comment]
"out of the group of people we have chosen in this conference, 100% have purple eyes"

doesnt make sense because we chose the people to be in the group.  out of the whole conference, it could only be 5% of people who do.

If there's any chart, i think a bar chart is better because it shows the total number.  

Dont get me wrong, i think its _great_ to say "we found 1300 incidents of this, 876 of that" because it shows the scale of what's going on.

**Comment by nikonikoniko** [comment]
does that make any more sense for my line of thinking?

**Comment by Hadi-Khatib** [comment]
I'm worried that we will be showing a false sense of statistics if we do the chart because you can see many chemical weapons incidents and very small number of violation of children rights for example. I think we need to verify much more to use the chart percentage.

**Comment by j-deutch** [comment]
Niko: Yeah you totally have self-selection bias, which is why you have to specify that it's of only observations that have been verified and categorised, not of observations or incidents in general. Having a visualisation of what is verified and categorised I feel helps show what's in the dataset.

Hadi: Cool. This makes a lot more sense. Maybe we hold off for now and to go back to it once more we have a few thousand more  verified and categorised.

**Comment by nikonikoniko** [comment]
@j-deutch i feel like hadi was making the same point i was :D 

i think looking at alternative ways to show what we have verified and how it's categorized is great.  I just dont think it will ever be a percentage based chart, cause that will always have our selection bias
